### ISSUE TITLE
Problem with icon size

### ISSUE THREAD

**Issue by spsf64** [archmerge/Halo-icons#1]
Hi Erik
I found the following errors with Halo icons too large...
The first is with Xfce (rhythmbox icon) when right click on desktop
The second with Cinnamon when right click on desktop or a folder (open as root).
Thanks

Xfce:
![xfce_rightclick](https://user-images.githubusercontent.com/1877391/31826006-a254349e-b592-11e7-8af7-0f4ca01b4641.png)

Cinnamon:
![cinnamonrightclick](https://user-images.githubusercontent.com/1877391/31826026-aceea006-b592-11e7-8b81-915faf358076.png)

**Comment by archmerge** [comment]
You are putting request on the wrong site.
I do not create the halo icons. They are not from me but from Alejandro.
Make an issue on his github.

[Halo github](https://github.com/Ampiflow/)
